# Configuration for welcome bot - https://github.com/behaviorbot/welcome
########################################################################################
# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  ðŸ‘‹ Thanks for opening your first issue here! Please make sure you filled out the template with as much detail as possible. You might also want to take a look at our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/GenericMappingTools/.github/blob/main/CODE_OF_CONDUCT.md).

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  ðŸ’– Thanks for opening this pull request! ðŸ’–

  Please make sure you read our [contributing guidelines](https://github.com/GenericMappingTools/pygmt/blob/main/CONTRIBUTING.md) and abide by our [code of conduct](https://github.com/GenericMappingTools/.github/blob/main/CODE_OF_CONDUCT.md).

  A few things to keep in mind:

  * If you need help writing tests, take a look at the existing ones for inspiration. If you don't know where to start, let us know and we'll walk you through it.
  * All new features should be documented. It helps to write the docstrings for your functions/classes before writing the code. This will help you think about your code design and results in better code.
  * No matter what, we are really grateful that you put in the effort to do this! ðŸŽ‰

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  ðŸŽ‰ðŸŽ‰ðŸŽ‰ Congrats on merging your first pull request and welcome to the team! ðŸŽ‰ðŸŽ‰ðŸŽ‰

  Please open a new pull request to add yourself to the `AUTHORS.md` file. We hope that this was a good experience for you. Let us know if there is any way that the contributing process could be improved.
