# Check links in the repository and documentation
#
# This workflow runs the lychee tool to check all external links in plaintext and HTML
# files. It will create an issue if broken links are found.
#
# It is scheduled to run weekly at 12 noon every Sunday.
#
name: Check Links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  # pull_request:
  workflow_dispatch:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'

permissions:
  issues: write

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    if: github.repository == 'GenericMappingTools/pygmt'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6.0.1
      with:
        path: repository
        persist-credentials: false

    - name: Checkout the documentation
      uses: actions/checkout@v6.0.1
      with:
        ref: gh-pages
        path: documentation
        persist-credentials: false

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
      with:
        fail: false  # Don't fail action on broken links
        output: /tmp/lychee-out.md
        # 200: OK
        # 429: Too many requests
        args: >
          --accept 200,429
          --exclude "^https://docs.generic-mapping-tools.org/6.[0-9]?/%s$"
          --exclude "^https://docs.generic-mapping-tools.org/6.[0-9]?/%3Cmodule-name%3E.html$"
          --exclude "^https://doi.org"
          --exclude "^https://github.com/%7Brepository%7D"
          --exclude "^https://github.com/GenericMappingTools/gmt/releases/tag/X.Y.Z$"
          --exclude "^https://github.com/GenericMappingTools/pygmt/edit"
          --exclude "^https://github.com/GenericMappingTools/pygmt/issues/new"
          --exclude "^https://github.com/GenericMappingTools/pygmt/pull/[0-9]*$"
          --exclude "^https://github.com/GenericMappingTools/pygmt/issues/[0-9]*$"
          --exclude "^https://github.com/GenericMappingTools/pygmt/releases/download/%7B%7Bpath%7D%7D/pygmt-docs.pdf"
          --exclude "^https://github.com/GenericMappingTools/pygmt/releases/download/%7B%7Bpath%7D%7D/pygmt-docs.zip"
          --exclude "^https://github.com/GenericMappingTools/pygmt/releases/tag/%7B%7Bpath%7D%7D"
          --exclude "^https://hackmd.io/@pygmt"
          --exclude "^https://test.pypi.org/simple/"
          --exclude "^https://www.adobe.com/jp/print/postscript/pdfs/PLRM.pdf"
          --exclude "^https://naciscdn.org/naturalearth"
          --exclude "^https://www.generic-mapping-tools.org/remote-datasets/%s$"
          --exclude "^https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html"
          --exclude "^https://www.pygmt.org/%7B%7Bpath%7D%7D"
          --exclude "^https://www.researchgate.net/"
          --exclude "^https://zenodo.org/badge/DOI/"
          --exclude "^https://stackoverflow.com/a/69170441"
          "repository/*.md"
          "repository/**/*.py"
          "documentation/dev/**/*.html"

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Issue From File
      if: steps.lychee.outputs.exit_code != 0
      run: |
        cd repository/
        title="Link Checker Report on ${CURRENT_DATE}"
        gh issue create --title "$title" --body-file /tmp/lychee-out.md
      env:
        GH_TOKEN: ${{ github.token }}
        CURRENT_DATE: ${{ steps.date.outputs.date }}
