# Support slash commands in pull requests
#
# Currently, only one slash command `format` is supported.
#
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
    # Add "edited" type for test purposes. Where possible, avoid using to prevent processing unnecessary events.
    # types: [created, edited]
jobs:
  slashCommandDispatch:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ github.token }}
          commands: |
            format
          issue-type: pull-request
          permission: none
